# Generated by Django 4.0.4 on 2022-05-14 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='payment',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], default=django.utils.timezone.now, max_length=50, verbose_name='Payment'),
            preserve_default=False,
        ),
    ]
