# Generated by Django 4.0.4 on 2022-05-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='eventCategory',
            new_name='eventCategories',
        ),
    ]
