# Generated by Django 4.0.4 on 2022-05-14 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_categories_remove_events_eventcategories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='eventCategories',
        ),
        migrations.AddField(
            model_name='events',
            name='eventCategories',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='Event Category'),
            preserve_default=False,
        ),
    ]
