# Generated by Django 4.0.4 on 2022-05-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_events_eventcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(default='upcoming', max_length=250, verbose_name='Status'),
        ),
    ]
