# Generated by Django 4.0.4 on 2022-05-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_events_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Event_Images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event', to='events.events')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
    ]
