# Generated by Django 4.0.4 on 2022-05-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_events_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='eventCategories',
        ),
        migrations.AddField(
            model_name='events',
            name='eventCategories',
            field=models.ManyToManyField(blank=True, max_length=500, null=True, to='events.categories', verbose_name='Event Category'),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(default='Upcoming', max_length=250, verbose_name='Status'),
        ),
    ]
