# Generated by Django 4.0.4 on 2022-05-15 08:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_events_eventcategories_events_eventcategories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='eventCategories',
        ),
        migrations.AddField(
            model_name='events',
            name='eventCategories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Activities', 'Activities'), ('Art', 'Art'), ('Bazar', 'Bazar'), ('Business', 'Business'), ('Concert', 'Concert'), ('Conference', 'Conference'), ('Dance', 'Dance'), ('Education', 'Education'), ('Exhibition', 'Exhibition'), ('Expo', 'Expo'), ('Fashion', 'Fashion'), ('Festival', 'Festival'), ('Film', 'Film'), ('Food', 'Food'), ('Fundraiser', 'Fundraiser'), ('Music', 'Music'), ('Online Webinar', 'Online Webinar'), ('Night Life', 'Night Life'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Travel', 'Travel'), ('Training', 'Training')], max_length=500, null=True, verbose_name='Event Category'),
        ),
    ]
