# Generated by Django 4.0.4 on 2022-05-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_events_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventDescription',
            field=models.TextField(verbose_name='Event Description'),
        ),
    ]
