# Generated by Django 4.0.4 on 2022-05-15 17:07

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_events_eventdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='photo',
            field=models.ImageField(upload_to='Event_Images/', validators=[events.models.Images.validate_image]),
        ),
    ]
