# Generated by Django 4.0.4 on 2022-05-16 03:04

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_images_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='venues',
            name='image',
            field=models.ImageField(upload_to='Venue Image/', validators=[events.models.validate_image], verbose_name='Venue Image'),
        ),
    ]
