# Generated by Django 4.0.4 on 2022-05-19 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_rename_photo_images_image_alter_venues_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='events',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 19, 10, 19, 19, 502844, tzinfo=utc), verbose_name='Date Added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 19, 10, 19, 34, 518185, tzinfo=utc), verbose_name='Date Added'),
            preserve_default=False,
        ),
    ]
