# Generated by Django 4.0.4 on 2022-05-21 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_cities_venues_date_added_venues_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventCity',
            field=models.ForeignKey(default='Ethiopia', on_delete=django.db.models.deletion.SET_DEFAULT, to='events.cities', verbose_name='Event City'),
        ),
    ]
