# Generated by Django 4.0.4 on 2022-05-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_events_eventcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventLocation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Event Location'),
        ),
    ]
