# Generated by Django 4.0.4 on 2022-06-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_events_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventCategories',
            field=models.CharField(blank=True, choices=[('Activities', 'Activities'), ('Art', 'Art'), ('Bazar', 'Bazar'), ('Business', 'Business'), ('Concert', 'Concert'), ('Conference', 'Conference'), ('Dance', 'Dance'), ('Education', 'Education'), ('Exhibition', 'Exhibition'), ('Expo', 'Expo'), ('Fashion', 'Fashion'), ('Festival', 'Festival'), ('Film', 'Film'), ('Food', 'Food'), ('Fundraiser', 'Fundraiser'), ('Music', 'Music'), ('Online Webinar', 'Online Webinar'), ('Night Life', 'Night Life'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Travel', 'Travel'), ('Training', 'Training')], max_length=500, null=True, verbose_name='Event Category'),
        ),
        migrations.AlterField(
            model_name='images',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.events', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='Event_Images/', verbose_name='Image'),
        ),
    ]
