# Generated by Django 4.0.4 on 2022-06-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_events_eventcategories_alter_images_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Event Image'),
        ),
    ]
