# Generated by Django 4.0.4 on 2022-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventWallet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
