# Generated by Django 4.0.4 on 2022-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_events_eventwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventCity',
            field=models.CharField(default='Addis Ababa', max_length=250, verbose_name='Event City'),
        ),
    ]
