# Generated by Django 4.0.4 on 2022-06-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_events_eventcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='organizerName',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Organizer Name'),
        ),
    ]
