# Generated by Django 4.0.4 on 2022-06-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_events_organizername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='organizerName',
        ),
        migrations.AddField(
            model_name='events',
            name='soldTickets',
            field=models.IntegerField(default=0, verbose_name='Sold Tickets'),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventWallet',
            field=models.PositiveIntegerField(default=0, verbose_name='Event Wallet'),
        ),
    ]
