version: "3"


services:
  db:
    image: postgres
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=eventTray_backend_2022
      - POSTGRES_USER=n
      - POSTGRES_PASSWORD=XwQuNb4TO8x9
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db