# Generated by Django 4.0.4 on 2022-05-03 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=500, unique=True, verbose_name='User Name')),
                ('firstName', models.CharField(blank=True, max_length=500, verbose_name='First Name')),
                ('lastName', models.CharField(blank=True, max_length=500, verbose_name='Last Name')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100, verbose_name='Gender')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter your phonenumber in the format starting with: 09 or +251', regex='^\\+?1?\\d{10,15}$')], verbose_name='Phone Number')),
                ('profilePicture', models.ImageField(default='Profile_Pictures/default.png', upload_to='Profile_Pictures/', verbose_name='Profile Picture')),
                ('counter', models.IntegerField(default=0)),
                ('role', models.CharField(blank=True, choices=[('User', 'User'), ('Event Organizer', 'Event Organizer'), ('Ticket Checker', 'Ticket Checker')], max_length=100, verbose_name='Role')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
