# Generated by Django 4.0.4 on 2022-05-03 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter your phonenumber in the format starting with: 09 or +251', regex='^\\+?1?\\d{10,15}$')], verbose_name='Phone Number'),
        ),
    ]
