# Generated by Django 4.0.4 on 2022-05-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coverPicture',
            field=models.ImageField(default='Cover_Pictures/cover.png', upload_to='Cover_Pictures/', verbose_name='Cover Picture'),
        ),
    ]
