# Generated by Django 4.0.4 on 2022-05-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_coverpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='rating',
            field=models.CharField(blank=True, default=0, max_length=150, null=True, verbose_name='Rating'),
        ),
    ]
