# Generated by Django 4.0.4 on 2022-05-05 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_managers_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter your phonenumber in the format starting with: 09', regex='^\\+?1?\\d{10}$')], verbose_name='Phone Number'),
        ),
    ]
