# Generated by Django 4.0.4 on 2022-05-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers_alter_user_phonenumber'),
        ('authentication', '0004_alter_user_phonenumber'),
    ]

    operations = [
    ]
