# Generated by Django 4.0.4 on 2022-05-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_merge_20220505_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rolea',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Event Organizer', 'Event Organizer'), ('Ticket Checker', 'Ticket Checker')], max_length=100, verbose_name='Role'),
        ),
    ]
