# Generated by Django 4.0.4 on 2022-06-09 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='tickets',
        ),
        migrations.AlterField(
            model_name='organizer',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='organizer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Organizer ID'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='twitter',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Twitter'),
        ),
    ]
