# Generated by Django 4.0.4 on 2022-05-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_rolea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rolea',
        ),
    ]
