# Generated by Django 4.0.4 on 2022-05-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_rolea'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verifiedUser',
            field=models.BooleanField(default=False),
        ),
    ]
