# Generated by Django 4.0.4 on 2022-06-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_organizer_tickets_alter_organizer_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='dailyVisitors',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='totalVisitors',
        ),
        migrations.AddField(
            model_name='organizer',
            name='eventsHosted',
            field=models.CharField(default=0, max_length=10, verbose_name='Events Hosted'),
        ),
    ]
