# Generated by Django 4.0.4 on 2022-06-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_organizer_dailyvisitors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='eventsHosted',
            field=models.PositiveIntegerField(default=0, verbose_name='Events Hosted'),
        ),
    ]
