# Generated by Django 4.0.4 on 2022-06-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_organizer_eventshosted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='events',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='eventsHosted',
        ),
        migrations.AddField(
            model_name='organizer',
            name='totalEvents',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Events'),
        ),
    ]
