# Generated by Django 4.0.4 on 2022-05-10 09:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('organizerPhone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Please enter your phonenumber in the format starting with: 09', regex='^\\+?1?\\d{10}$')], verbose_name='Organizer Phone')),
                ('twitter', models.CharField(blank=True, max_length=150, null=True, verbose_name='Twitter Link')),
                ('telegram', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram Link')),
                ('instagram', models.CharField(blank=True, max_length=150, null=True, verbose_name='Instagram Link')),
                ('commercialLicense', models.FileField(blank=True, null=True, upload_to='Commercial_License', verbose_name='Commercial License')),
                ('idCard', models.FileField(blank=True, null=True, upload_to='Id_Card', verbose_name='Id Card')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('verifiedOrganizer', models.BooleanField(default=False)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organizer')),
            ],
            options={
                'verbose_name_plural': 'Organizer Details',
            },
        ),
    ]
