# Generated by Django 4.0.4 on 2022-05-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_is_authenticated_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verifiedUser',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='None', max_length=100, verbose_name='Gender'),
        ),
    ]
