# Generated by Django 4.0.4 on 2022-06-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_organizer_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='totalEvents',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total Events'),
        ),
    ]
