# Generated by Django 4.0.4 on 2022-06-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_organizer_totalevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='wallet',
            field=models.CharField(blank=True, default=0, max_length=150, null=True, verbose_name='Wallet'),
        ),
    ]
