# Generated by Django 4.0.4 on 2022-05-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_user_verifieduser_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='commercialLicense',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='idCard',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='organizerPhone',
        ),
        migrations.AddField(
            model_name='organizer',
            name='verifyingDocument',
            field=models.FileField(blank=True, null=True, upload_to='Verifying_Document', verbose_name='Verifying Document'),
        ),
    ]
