# Generated by Django 4.0.4 on 2022-05-11 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_organizer_commerciallicense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter your phonenumber in the format starting with: 09', regex='^\\+?1?\\d{10}$')], verbose_name='Phone Number'),
        ),
    ]
