# Generated by Django 4.0.4 on 2022-05-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Organizer', 'Organizer'), ('Checker', 'Checker')], max_length=100, verbose_name='Role'),
        ),
    ]
