# Generated by Django 4.0.4 on 2022-05-19 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0016_remove_events_date_joined_events_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketName', models.CharField(max_length=150, verbose_name='Ticket Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('ticketPerUser', models.IntegerField(verbose_name='Ticket Sell per User')),
                ('soldTickets', models.IntegerField(verbose_name='Sold Tickets')),
                ('startSellOn', models.DateField(verbose_name='Start Sell on')),
                ('endSellOn', models.DateField(verbose_name='End Sell on')),
                ('is_active', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events', verbose_name='Event')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
