# Generated by Django 4.0.4 on 2022-05-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='soldTickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sold Tickets'),
        ),
    ]
