# Generated by Django 4.0.4 on 2022-05-19 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_tickets_soldtickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='endSellOn',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='startSellOn',
        ),
        migrations.AddField(
            model_name='tickets',
            name='endSaleOn',
            field=models.DateField(default=datetime.datetime(2022, 5, 19, 10, 55, 55, 623494, tzinfo=utc), verbose_name='End Sale on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='startSaleOn',
            field=models.DateField(default=datetime.datetime(2022, 5, 19, 10, 56, 1, 422427, tzinfo=utc), verbose_name='Start Sale on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='ticketDescription',
            field=models.TextField(blank=True, null=True, verbose_name='Ticket Description'),
        ),
    ]
