# Generated by Django 4.0.4 on 2022-05-29 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_tickets_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price per Unit'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='soldTickets',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sold Tickets'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticketPerUser',
            field=models.PositiveIntegerField(verbose_name='Ticket Sell per User'),
        ),
    ]
