# Generated by Django 4.0.4 on 2022-06-10 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0005_alter_tickets_price_alter_tickets_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='ticketOwner',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ticket Owner'),
            preserve_default=False,
        ),
    ]
