# Generated by Django 4.0.4 on 2022-06-12 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_events_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0006_tickets_ticketowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='eventName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Name'),
        ),
        migrations.CreateModel(
            name='TicketsBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Name')),
                ('phoneNumber', models.CharField(max_length=50, verbose_name='Buyer Phone')),
                ('orderNo', models.CharField(max_length=50, verbose_name='Order Number')),
                ('buyerName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buyer Name')),
                ('qrCode', models.CharField(max_length=50, verbose_name='QR Code')),
                ('is_payed', models.BooleanField(default=False)),
                ('is_scanned', models.BooleanField(default=False)),
                ('datePuchased', models.DateField(auto_now_add=True, verbose_name='Date Purchased')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events', verbose_name='Event')),
            ],
            options={
                'verbose_name_plural': 'Tickets Bought',
            },
        ),
    ]
