# Generated by Django 4.0.4 on 2022-06-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_tickets_eventname_ticketsbought'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsbought',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Price'),
        ),
    ]
