# Generated by Django 4.0.4 on 2022-06-12 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticketsbought_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsbought',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.tickets', verbose_name='Ticket'),
            preserve_default=False,
        ),
    ]
