# Generated by Django 4.0.4 on 2022-06-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_tickets_ticketperuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='soldTickets',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sold Tickets'),
        ),
    ]
