# Generated by Django 4.0.4 on 2022-06-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_tickets_soldtickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsbought',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
