# Generated by Django 4.0.4 on 2022-06-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticketsbought_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsbought',
            name='image',
        ),
        migrations.AddField(
            model_name='tickets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='merchs/'),
        ),
    ]
