# Generated by Django 4.0.4 on 2022-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=200)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('isSent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
